name: Build and Deploy MkDocs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Build MkDocs site
        run: mkdocs build
        
      - name: Deploy to GitHub Pages branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r site/* .
          touch .nojekyll
          git add -A
          git commit -m "Deploy MkDocs site to GitHub Pages"
          git push -f origin gh-pages